### ISSUE TITLE
Unable to watch Live TV

### ISSUE THREAD

**Issue by daurora58** [jumpmanjay/HDGrandSlam.bundle#1]
Hi Jumpmanjay:

Could you please review the enclosed log, to establish the reason why I am unable to watch Live TV with this app? As I have mentioned in past posts, I am able to view Recorded shows using your app, however Live TV produces an error message as follows: The Transcoder failed to start...

Thank you,
daurora
[Plex_ErrorOnLiveTV.txt](https://github.com/jumpmanjay/HDGrandSlam.bundle/files/440308/Plex_ErrorOnLiveTV.txt)

**Comment by jumpmanjay** [comment]
I don't know what kind of log file that is- it doesn't provide any helpful information.

Can you run the following at the command prompt in the [PMS]/Plug-Ins/HDGrandSlam.bundle/Contents/Services/Shared Code/ directory:

`python`
`import imp`
`pm = imp.load_source("PyHDHR","PyHDHR.pys")`
`p = getattr(pm,"PyHDHR")()`
`p.discoveryDump("dump.txt")`

Then post the dump.txt file as well as the plug-in logs (com.plexapp.plugins.hdgrandslam.log).

**Comment by daurora58** [comment]
Hi:

I am running Windows 10 (Intel i3) and tried running the script (line by line) with in the indicated folder; within the command prompt.

As you can imagine, Windows 10 doesn’t even understand the first line “python”.

Can you suggest some other method for getting this information to you, for me – a non programmer 😉.

Thanks,

daurora

**Comment by jumpmanjay** [comment]
Your server should have Python installed...

...if not, try installing 2.7.

**Comment by daurora58** [comment]
Hi jumpmanjay

I tried installing Python 2.7 on the pc with Plex Server, however, I could not run the code you asked...like I said I am not a programmer.

All is not lost, since after playing around with some parameters, I have been able to make the Live TV functionality work. I did the following two actions to make Live TV work in my environment:

1) On the SiliconDust Extend webpage (for me: 192.168.1.122) I set the "Default Transcode Profile" to None.

2) On your HDGrandSlam plugin settings, I ensured that the Checkbox is ON (Checked) for "Use configured default transcode profile on Extend tuner for Live TV".

Please note - I have one Connect tuner (192.168.1.123) and one Extend tuner (192.168.1.`122) in this single subnet; and after making the above configuration changes I now have live tv.

Many thanks for making such a needed app, I hope the information I have provided to you will further assist you in fortifying this app.

daurora

**Comment by jumpmanjay** [comment]
I'm glad it's finally working for you, but leaving the check box unchecked
essentially configures it to how yours is now configured- setting the
transcode to none.
