### ISSUE TITLE
Multiple front ends accessing one steam - possible?

### ISSUE THREAD

**Issue by Gremlyn** [jumpmanjay/HDGrandSlam.bundle#11]
This might be a limitation of Plex, but is it possible to have the channel look to see if a stream exists from the server so that multiple front ends access the same feed? I have tried to watch the same TV channel on two Roku Plex installs and often this doesn't work with one of the devices having jittery, pixelated video. I assume that is due to the server trying to transcode the feed twice.

**Comment by jumpmanjay** [comment]
SiliconDust's API allows for this- I tried, but could not get this to work via Plex. Everything looked like it was working, but the video would just not display.
