### ISSUE TITLE
this channel broke in PMS 1.4.1

### ISSUE THREAD

**Issue by tachtevrenidis** [jumpmanjay/HDGrandSlam.bundle#16]
feel free to close this if I am the only one who experiences this, but after I upgraded to the latest PMS (1.4.1 came out a couple of days ago), no Plex clients works withHDGrandSlam (used to work just fine).

**Comment by jumpmanjay** [comment]
Problem verified. Will try to get this to work later.

**Comment by jumpmanjay** [comment]
Please use v1.6.3
