### ISSUE TITLE
Using any Extend tuner transcode scheme other than None causing Live TV stream failure

### ISSUE THREAD

**Issue by daurora58** [jumpmanjay/HDGrandSlam.bundle#2]
Hi Jumpmanjay:

As the title says, if I select any transcode scheme on my Extend tuner, other than : None; then I get a session failure. Please note: The following initial condition are true:

1) On your HDGrandSlam plugin settings, Checkbox is OFF (Unchecked) for "Use configured default transcode profile on Extend tuner for Live TV".

2) On the SiliconDust Extend webpage (for me: 192.168.1.122) I set the "Default Transcode Profile" to any other transcode scheme other thatn "None".

I would like the choice to select a transcode scheme for the Extend tuner. 

Please note I have enclosed the error log files from your 1.3 version.

Thanks,
daurora
[com.plexapp.plugins.hdgrandslam.log.zip](https://github.com/jumpmanjay/HDGrandSlam.bundle/files/446011/com.plexapp.plugins.hdgrandslam.log.zip)

**Comment by jumpmanjay** [comment]
I tested this with 2 clients (Chrome on Windows 10 and a Nexus 6P). With the "use configured default transcoding profile on Extend tuners for live TV" setting checked, I tested both devices in all transcode configurations (none, heavy, mobile, internet540, internet480, internet360, and internet240) without issue. Unchecking the setting, of course reverts it back to a transcode of "none."

If you are having issues, the problem might be with your client device.
