### ISSUE TITLE
Error On Playback

### ISSUE THREAD

**Issue by yaryarrr** [jumpmanjay/HDGrandSlam.bundle#22]
When trying to play live tv, I get the following error:

> An error occurred trying to play "SHOW NAME".
> shaka1001 (Network)

Running Plex Version 1.10.0.4523
Plugin Version 1.6.3
MacOS 10.12.6
Client: Safari Web, iOS

**Comment by jumpmanjay** [comment]
Was this working previously?

Do you have any server logs?

**Comment by jumpmanjay** [comment]
Please try version 1.6.4

**Comment by yaryarrr** [comment]
I pulled the master branch, and it's working. Thanks!
