### ISSUE TITLE
Unable to find Tuner (Add ability to define HDHR IP manually)

### ISSUE THREAD

**Issue by karbowiak** [jumpmanjay/HDGrandSlam.bundle#4]
Hi there.

So i'm using a somewhat weirdish setup, i have my server (with plex) and my router, both connected to the same modem - with each their own IP.

My server is also connected to the Router, so server has a public IP and an internal LAN IP.
But when i try and open HDGrandSlam, it can't find anything - so i looked at the log, and noticed the http://my.hdhomerun.com/discover url being accessed, and tried it on my desktop - where it gave me the IP and other info about my HDHR just fine.

Tried the same on the server via lynx (and php file_get_contents) and it's instead null.

So it seems that the my.hdhomerun.com page can't figure out what my local network IP is, and thus can't find the HDHR.

Any chance of adding so that the HDHR's IP can be defined manually? :)

**Comment by jumpmanjay** [comment]
Check out release 1.6. You can now specify the tuner IP(s) manually, but beware you won't get any guide data, as that would still need to be resolved to my.hdhomerun.com. You should still be able to manually tune to the station you want.
